### ISSUE TITLE
Compiling in 32 bits?

### ISSUE THREAD

**Issue by trebmuh** [nicoroulet/moog#2]
Reading [at the makefile](https://github.com/nicoroulet/moog/blob/master/Makefile), it looks that compiling in 64 bits mode is hardcoded. Could you please make it so that it autodetects if the system is 32 or 64 bits and then compile it accordingly?

**Comment by jpcima** [comment]
`-m64` can go away if you use the generic, non-asm optimized make target, which is the default one (because it's the `cpp` target and it's at the top).

About the SIMD optimizations on the asm side, there would be surely a way to preserve them mostly in a 32/64 compatible setting. I guess one way would to be to re-express them in C source, using some compiler-provided extensions. (example: OpenMP, x86 SIMD intrinsics)

**Comment by trebmuh** [comment]
OK, ty @jpcima
@nicoroulet please, consider merging https://github.com/nicoroulet/moog/pull/7

**Comment by trebmuh** [comment]
Closing now it has been merged in master. Thank you both.
